Versus
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-CapTeam_America pull request #13
Opened 2023-11-16 08:45 UTC by Leslie2186

2023-11-16 08:51 UTC, Defreitasnicolas approved these changes

2023-11-17 07:31 UTC, jujuck requested changes

2023-11-17 07:31 UTC, jujuck commented on frontend/src/App.css
> +  /*background-image: url("../public/background-hero.png");
Pas de code mort

2023-11-17 07:31 UTC, jujuck commented on frontend/src/components/cards/Cards.jsx
> +  const { avatar1, setAvatar1 } = useContext(SuperheroContext);
On peut tout récupérer en une seule ligne { ...}

2023-11-17 07:31 UTC, jujuck commented on frontend/src/components/versus/Versus.css
> +.combattant1Img,
Remplacer les combattant par fighter pour uniformiser le nom des class css

2023-11-17 07:31 UTC, jujuck commented on frontend/src/components/versus/Versus.css
> +.combattant2Img,
idem

2023-11-17 07:31 UTC, jujuck commented on frontend/src/components/versus/Versus.css
> +.combattant1Img {
idem

2023-11-17 07:31 UTC, jujuck commented on frontend/src/components/versus/Versus.css
> +.combattant2Img {
idem

2023-11-17 07:31 UTC, jujuck commented on frontend/src/components/versus/Versus.css
> +  .combattant1Img {
idem

2023-11-17 07:31 UTC, jujuck commented on frontend/src/components/versus/Versus.css
> +  .combattant1Img {
...

2023-11-17 09:48 UTC, closed without merging