fix des propriétés CSS suite à l'ajout du filtre
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-CapTeam_America pull request #20
Opened 2023-11-20 16:20 UTC by MaximeG971

2023-11-20 16:22 UTC, Leslie2186 requested changes

2023-11-20 16:22 UTC, Leslie2186 commented on frontend/src/pages/Cardheros.jsx
Retirer les commentaires

2023-11-20 16:25 UTC, Leslie2186 approved these changes

2023-11-21 09:24 UTC, aimach requested changes

2023-11-21 09:24 UTC, aimach commented on frontend/src/components/favoris/Favoris.jsx
> +      <h1 className="titleFavoris">
Mettre plutôt un h2

2023-11-21 09:55 UTC, aimach approved these changes

2023-11-21 09:55 UTC, merged