Affichage 8 cards en mode desktop et 4 en mode mobile
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-CapTeam_America pull request #5
Opened 2023-11-07 10:05 UTC by Leslie2186

2023-11-07 10:11 UTC, Defreitasnicolas approved these changes

2023-11-07 10:38 UTC, jujuck requested changes

2023-11-07 10:38 UTC, jujuck commented on frontend/src/App.jsx
> +    axios
Mettre la requete de chargement sur le loader de la route dans main.jsx puis utiliser le useLoaderData

2023-11-07 10:38 UTC, jujuck commented on frontend/src/components/cardheros/Cardheros.jsx
> +  const count = window.innerWidth > 765 ? 8 : 4;
Prendre la mesure dans le loader de la page (dans main.jsx) puis passer l'information en query de requete pour ne récupérer que le nombre d'élément souhaité. Cela évitera également le filter dans le return

2023-11-07 10:38 UTC, jujuck commented on frontend/src/components/cards/Cards.css
> +p#titleName {
Eviter les ID autant que possible car réserver à React, mettre une classe CSS avec le même nom

2023-11-07 10:38 UTC, jujuck commented on frontend/src/components/cards/Cards.css
> +p#titleRace {
Eviter les ID autant que possible car réserver à React, mettre une classe CSS avec le même nom

2023-11-07 10:38 UTC, jujuck commented on frontend/src/components/cards/Cards.jsx
> +        <p id="titleName">{hero.name.toUpperCase()}</p>
Eviter les ID autant que possible car réserver à React, mettre une classe CSS avec le même nom

2023-11-07 10:38 UTC, jujuck commented on frontend/src/components/cards/Cards.jsx
> +        <p id="titleRace">{hero.race}</p>
Eviter les ID autant que possible car réserver à React, mettre une classe CSS avec le même nom

2023-11-07 15:02 UTC, MaximeG971 approved these changes

2023-11-07 15:02 UTC, MaximeG971 approved these changes

2023-11-07 15:03 UTC, MaximeG971 approved these changes

2023-11-07 15:03 UTC, MaximeG971 approved these changes

2023-11-08 11:09 UTC, jujuck requested changes

2023-11-08 11:09 UTC, jujuck commented on frontend/src/App.css
> +  background-image: url("./assets/background-hero.png");
Pas d'image depuis les assets

2023-11-08 11:09 UTC, jujuck commented on frontend/src/App.css
> +    background-image: url("./assets/background-desktop.png");
Pas d'image venant des assets

2023-11-08 11:09 UTC, jujuck commented on frontend/src/main.jsx
> +        .then((response) => response.data[0])
Non, le [0] doit être mis en back end. Pas d'over fetching

2023-11-08 11:09 UTC, jujuck commented on backend/src/router.js
> +    .then((result) => res.status(200).json(result))
Mettre result[0] ou destructurer au moment de la récupération

2023-11-08 11:09 UTC, jujuck commented on frontend/src/components/cards/Cards.jsx
> +    <div key={hero.slug} className="cardHero">
Pas de key dans le composant

2023-11-08 11:09 UTC, jujuck commented on frontend/src/components/cards/Cards.jsx
> +        <img src={elipsePoing} alt="Ellipse Poing" className="poing" />
Pas de français, poing => fist (idem, nom de l'image)

2023-11-08 14:00 UTC, Phoulos approved these changes

2023-11-08 14:18 UTC, jujuck approved these changes

2023-11-08 14:19 UTC, merged