Show one card
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-CapTeam_America pull request #7
Opened 2023-11-10 10:27 UTC by MaximeG971

2023-11-10 10:30 UTC, Defreitasnicolas approved these changes

2023-11-13 15:53 UTC, jujuck requested changes

2023-11-13 15:53 UTC, jujuck commented on backend/src/router.js
> +        res.json(superhero[0]);
Peux tu préciser un status de réussite à ta requête (200) => res.status(200).json(superhero[0])

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/cards/Cards.jsx
> +        <button type="button" onClick={<CompleteCard heroId={hero.id} />}>
Quelle est l'intention derrière cette action ? Besoin d'en discuter

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardDesktop.css
> +  li {
Attention en mettant du style sur le li, tous les li de l'application vont être concerné. 2 possibilités : mettre une classe CSS particulière pour les li de la carte ou mettre le style des li dans app.css

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardDesktop.jsx
> +import "./CardDesktop.css";
Mettre les import de librairie en premier pour les autres

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardDesktop.jsx
> +          <h1 className="superHeroName">{oneSuperHero.name}</h1>
Attention un seul H1 par page... Si tu veux mettre les 2 infos, pense à la balise span

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardDesktop.jsx
> +            <li>
Créer un composant réutilisable pour ta balise li  + img avec des props pour src, alt et className

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardMobile.jsx
> +        <ul>
Créer un composant de UL réutilisé dans tes 2 composants (mobile et desktop)

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardDesktop.jsx
> +        <ul>
Créer un composant de UL réutilisé dans tes 2 composants (mobile et desktop)

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardDesktop.jsx
> +            <li>
Tu pourras réutiliser le composant dans ton autre composant Mobile

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardMobile.jsx
> +          <li>
Créer un composant pour ton li et img, Tu pourras réutiliser le composant dans ton autre composant Mobile

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardMobile.jsx
> +          <h1 className="superHeroName">{oneSuperHero.name}</h1>
Un seul titre par page

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardMobile.css
> +.completeCard {
Pense à mettre ce qui est identique entre le CardDesktop et CardMobile dans un fichier partagé. Ne garde ici que ce qui est spécifique au Mobile

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardMobile.css
> +img {
Attention, tu mets un style sur toutes les img de ton app... Pense à utiliser une classe spécifique

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardDesktop.css
> +@media only screen and (min-width: 765px) {
Pense à mettre ce qui est identique entre le CardDesktop et CardMobile dans un fichier partagé. Ne garde ici que ce qui est spécifique au Mobile

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardMobile.css
> +li {
NE pas mettre de style directement sur le li, pense à faire une classe CSS

2023-11-13 15:53 UTC, jujuck commented on frontend/src/components/completeCard/CardMobile.css
> +h2 {
NE pas mettre de style directement sur le h2, pense à faire une classe CSS

2023-11-14 14:52 UTC, Defreitasnicolas approved these changes

2023-11-14 15:10 UTC, Leslie2186 approved these changes

2023-11-14 15:32 UTC, jujuck approved these changes

2023-11-14 15:32 UTC, merged