Création de la fonctionnalité filtre et mis en place du logo
WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-CapTeam_America pull request #8
Opened 2023-11-14 09:47 UTC by Phoulos

2023-11-14 10:56 UTC, Leslie2186 approved these changes

2023-11-14 11:09 UTC, Leslie2186 requested changes, later dismissed

2023-11-14 11:09 UTC, Leslie2186 commented on frontend/src/App.jsx
Refaire indentation, créer component pour la Navbar et l'appeler dans App.jsx

2023-11-14 11:09 UTC, Leslie2186 commented on frontend/src/App.css
Mettre le css à part dans le dossier du component Navbar

2023-11-16 07:53 UTC, aimach commented
Il y a un conflit à résoudre avant la review formateur !

2023-11-17 07:41 UTC, jujuck submitted a review, later dismissed
Plus attention au linter qui bloque

2023-11-17 07:41 UTC, jujuck commented on frontend/src/App.jsx
> +        .get(`${import.meta.env.VITE_BACKEND_URL}/api/superheros`)
Mettre un ternaire directement dans l'url du get pour faire la condition 
const query = `?race={$SelectedRace}` ;
 `${import.meta.env.VITE_BACKEND_URL}/api/superheros${selectedRace === "_all_" ? "" : query
} `

2023-11-17 07:41 UTC, jujuck commented on frontend/src/components/cardheros/Cardheros.jsx
> +  if (!superheros) {
Arrange toi pour récupérer un tableau dans tous les cas de figures. Dans ce cadre, tu n'auras pas besoin de ces 3 lignes

2023-11-17 15:34 UTC, aimach commented
Régler les conflits svp !

2023-11-17 16:00 UTC, aimach requested changes

2023-11-17 16:04 UTC, aimach approved these changes

2023-11-17 19:50 UTC, Leslie2186 approved these changes

2023-11-20 06:24 UTC, merged